/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EntryLog = IDL.Record({
  'result' : IDL.Text,
  'passengerName' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'faceHash' : IDL.Text,
  'membershipTier' : IDL.Text,
});
export const VerificationResult = IDL.Record({
  'verificationTime' : IDL.Int,
  'accessGranted' : IDL.Bool,
  'passengerName' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'membershipTier' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntryLogs' : IDL.Func([], [IDL.Vec(EntryLog)], ['query']),
  'getMemberById' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'simulateVerification' : IDL.Func([IDL.Text], [VerificationResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EntryLog = IDL.Record({
    'result' : IDL.Text,
    'passengerName' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'faceHash' : IDL.Text,
    'membershipTier' : IDL.Text,
  });
  const VerificationResult = IDL.Record({
    'verificationTime' : IDL.Int,
    'accessGranted' : IDL.Bool,
    'passengerName' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'membershipTier' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntryLogs' : IDL.Func([], [IDL.Vec(EntryLog)], ['query']),
    'getMemberById' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'simulateVerification' : IDL.Func([IDL.Text], [VerificationResult], []),
  });
};

export const init = ({ IDL }) => { return []; };